  <div class="banner">

                <!-- **Slider Section** -->
                <div id="layerslider_9" class="ls-wp-container" style="width:100%;height:500px;max-width:1920px;margin:0 auto;margin-bottom: 0px;">
                    <div class="ls-slide" data-ls="slidedelay:10000;transition2d:4;">
                        <img src="/images/sliders/blank.gif" data-src="/images/fondo-azul.jpg" class="ls-bg" alt="bg3" />
                        <p class="ls-l" style="top:346px;left:1013px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:7000;"> <a href="/productos/herramientas-de-desbaste/esmeriles/" class="dt-sc-button1 ico-button"> Ver más</a></p>
                        <div class="ls-l" style="top:178px;left:1069px;font-weight:bolder; z-index:4;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:17px;line-height:46px;color:#7EC8DF;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-100;durationin:2000;delayin:2500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;">AXMO-21</div>
                        <div class="ls-l" style="top:259px;left:655px;font-weight:bolder;letter-spacing:4.3px; z-index:3;font-family:'Lato';font-size:26.5px;line-height:20px;color:rgb(162,171,184);white-space: nowrap;" data-ls="offsetxin:-100;durationin:2000;delayin:4000;"> Los esmeriles <strong>  Airon Tools  </strong> están</div>
                        <div class="ls-l" style="top:299px;left:655px;font-weight:bolder;letter-spacing:2px; z-index:3;font-family:'Lato';font-size:26.5px;line-height:20px;color:rgb(162,171,184);white-space: nowrap;" data-ls="offsetxin:-100;durationin:2000;delayin:4000;"><strong></strong>  diseñadospara el trabajo más pesado</div>
                        <div class="ls-l" style="top:120px;left:655px;font-weight:700; z-index:3;font-family:'Lato'; letter-spacing: 3.6px; font-size:43px;line-height:20px;color:rgb(255,255,255);white-space: nowrap;" data-ls="offsetxin:0;offsetyin:50;durationin:2000;delayin:3000;">Esmeriles Neumáticos</div>
                        <div class="ls-l" style="top:183px;left:655px;font-weight:700; z-index:3;font-family:'Lato'; letter-spacing:14px; font-size:43px;line-height:20px;color:rgb(255,255,255);white-space: nowrap;" data-ls="offsetxin:0;offsetyin:50;durationin:2000;delayin:3000;">Industriales </div>
                        <div class="ls-l" style="top:105px;left:787px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:3000;"><span style="background: #00a5df; color: #fff; display: inline-block; font-family: 'Lato', sans-serif; font-size: 20px; font-weight: 300; line-height: 24px; margin: 10px 0 0; padding: 0 7px 0 7px; position: relative; text-decoration: none; border-radius: 3px; -webkit-border-radius: 3px; -moz-border-radius: 3px; -ms-border-radius: 3px; -o-border-radius: 3px; "></span></div>
                        <img class="ls-l" style="top:0px;left:0px;white-space: nowrap; " data-ls="offsetxin:0;offsetyin:300;durationin:1500;delayin:500;" src="/images/sliders/blank.gif" data-src="/images/MINIESMERIL-INDUSTRIAL-AXMO-21.jpg" alt="Mini esmeril industrial-axmo-21" title="Mini esmeril industrial-axmo-21">
                        
                    </div>
                    <div class="ls-slide" data-ls="slidedelay:10000;transition2d:4;">
                        <img src="/images/sliders/blank.gif" data-src="/images/fondo-azul.jpg" class="ls-bg" alt="bg1" />
                        <div class="ls-l" style="top:66px;left:0px;font-weight:900; z-index:5; letter-spacing: 1.3px;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:43px;line-height:53px;color:rgb(255,255,255);white-space: nowrap;" data-ls="offsetxin:0;offsetyin:200;durationin:2500;delayin:3500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;"> <br><span style="color:rgb(255,255,255);">Remachadora de Clavillo</span> </div>
                        <div class="ls-l" style="top:200px;left:0px;font-weight:300; z-index:5;letter-spacing:2.6px;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:27px;line-height:60px;color:rgb(209,208,206);white-space: nowrap;" data-ls="offsetxin:0;offsetyin:200;durationin:2500;delayin:1500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;">La gama más amplia de remachadoras <br></div>
                        <div class="ls-l" style="top:264px;left:0px;font-weight:300;z-index:3;letter-spacing:1.7px;font-family:'Lato';font-size:27px;line-height:26px;color:#A2ABB8;white-space: nowrap;" data-ls="offsetxin:-100;durationin:2000;delayin:2500;">industriales las tenemos en <span style="color:#21c2f8;">&nbsp;Airon tools</span> </div>
                        <div class="ls-l" style="top:190px;left:0px;z-index: display:block;width:514px;height:2px;border-bottom:1px solid rgb(001,168,223);font-family:'Ubuntu';font-size:24px;line-height:34px;color:rgb(001,168,223);background:rgb(001,168,223);white-space: nowrap;" data-ls="offsetxin:-500;durationin:2500;delayin:4500;"><br> </div>
                        <img class="ls-l" style="top:0px;left:570px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-100;delayin:500;" src="/images/sliders/blank.gif" data-src="/images/Remachadora-de-Clavillo.jpg" alt="Remachadora de clavillo" title="Remachadora de clavillo">
                        <p class="ls-l" style="top:334px;left:379px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:7000;"> <a href="/productos/remachadoras/de-clavillo/" class="dt-sc-button1 ico-button"> Ver más</a></p>
                    </div>
                    <div class="ls-slide" data-ls="slidedelay:10000;transition2d:4;">
                        <img src="/images/sliders/blank.gif" data-src="/images/fondo-azul.jpg" class="ls-bg" alt="bg2" />
                        <div class="ls-l" style="top:130px;left:0px;font-weight:normal; letter-spacing: 3.7px;z-index:5;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:40px;line-height:46px;color:#FFFFFF;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-100;durationin:2000;delayin:2500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;">Remachadoras de Tuerca</div>
                        <div class="ls-l" style="top:141px;left:0px;font-weight:normal; z-index:5;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:60px;line-height:46px;color:#FFFFFF;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-100;durationin:2000;delayin:2500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;"></div>
                        <div class="ls-l" style="top:157px;left:0px;font-weight:300; z-index:3; letter-spacing:5.5px;font-family:'Lato';font-size:43px;line-height:26px;color:#101017;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;durationin:2000;delayin:3500;"></div>
                        <div class="ls-l" style="top:223px;left:0px;font-weight:300;font-family:'Lato';font-size:24px;color:#101017;white-space: nowrap;" data-ls="delayin:4500;"><span style="color:#00a5df; font-weight:700;"></span></div>
                        <img class="ls-l" style="top:0px;left:570px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:500;durationin:1800;" src="/images/sliders/blank.gif" data-src="/images/REMACHADORA-DE-TUERCAS-ATRE-7.jpg" alt="Remachadora de tuercas Atre 7" title="Remachadora de tuercas Atre 7">
                        <div class="ls-l" style="top:202px;left:0px;font-weight:300;letter-spacing: 2.3px;font-family:'Lato';font-size:27px;color:#101017;white-space: nowrap;" data-ls="delayin:5000;"><span style="color:rgb(209,208,206); font-weight:700;">Contamos con las remachadoras que</span></div>
                        <div class="ls-l" style="top:244px;left:0px;font-weight:300;letter-spacing:.3px;font-family:'Lato';font-size:27px;color:#101017;white-space: nowrap;" data-ls="delayin:5500;"><span style="color:rgb(209,208,206);; font-weight:700;">necesitas para tus aplicaciones de tuercas</span> </div>
                        <div class="ls-l" style="top:313px;left:0px;font-weight:300;font-family:'Lato';font-size:20px;color:#101017;white-space: nowrap;" data-ls="delayin:6000;"><span style="color:#00a5df; font-weight:700;"></span></div>
                        <p class="ls-l" style="top:303px;left:380px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:7000;"> <a href="/productos/remachadoras/tuerca-inserto/" class="dt-sc-button1 ico-button"> Ver más</a></p>
                    </div>
                    <div class="ls-slide" data-ls="slidedelay:10000;transition2d:4;">
                        <img src="/images/sliders/blank.gif" data-src="/images/fondo-azul.jpg" class="ls-bg" alt="bg3" />
                        <div class="ls-l" style="top:70px;left:1075px;font-weight:300; z-index:5;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:44px;line-height:46px;color:#101017;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-100;durationin:2000;delayin:2500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;"></div>
                        <div class="ls-l" style="top:264px;left:657px;letter-spacing:2.2px; font-weight:normal; z-index:3;font-family:'Lato';font-size:27px;line-height:40px;color:#a2abb8;white-space: nowrap;" data-ls="offsetxin:-100;durationin:2000;delayin:4000;">Las nuevas, mejores y más potentes</div>
                        <div class="ls-l" style="top:302px;left:657px;letter-spacing:1.2px; font-weight:normal; z-index:3;font-family:'Lato';font-size:27px;line-height:40px;color:#a2abb8;white-space: nowrap;" data-ls="offsetxin:-100;durationin:2000;delayin:4000;"><strong>llaves de impacto</strong> las encuentras aqui! </div>
                        <div class="ls-l" style="top:136px;left:723px;font-weight:700;z-index:3;font-family:'Lato';font-size:45px;line-height:26px;color:#FFFFFF;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:50;durationin:2000;delayin:3000;"> Llaves de Impacto</div>
                        <div class="ls-l" style="top:59px;left:1016px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:3000;"><span style="background: #00a5df; color: #fff; display: inline-block; font-family: 'Lato', sans-serif; font-size: 20px; font-weight: 300; line-height: 24px; margin: 10px 0 0; padding: 0 7px 0 7px; position: relative; text-decoration: none; border-radius: 3px; -webkit-border-radius: 3px; -moz-border-radius: 3px; -ms-border-radius: 3px; -o-border-radius: 3px; "></span> </div>
                        <img class="ls-l" style="top:66px;left:656px;width:494px;white-space: nowrap;" data-ls="durationin:1600;delayin:3500;rotateyin:90;" src="/images/sliders/blank.gif" data-src="/images/sliders/quote.png" alt="image">
                        <img class="ls-l" style="top:0px;left:0px;white-space: nowrap; " data-ls="offsetxin:0;offsetyin:300;durationin:1500;delayin:500;" src="/images/sliders/blank.gif" data-src="/images/Llave-de-Impacto.jpg" alt="Llave de impacto" title="Llave de impacto">
                        <p class="ls-l" style="top:357px;left:1013px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:7000;"> <a href="/productos/llaves-de-impacto/" class="dt-sc-button1 ico-button"> Ver más</a></p>
                    </div>
                    <div class="ls-slide" data-ls="slidedelay:10000;transition2d:4;">
                        <img src="/images/sliders/blank.gif" data-src="/images/fondo-azul.jpg" class="ls-bg" alt="bg1" />
                        <div class="ls-l" style="top:127px;left:0px;font-weight:300; z-index:5;padding-left:0px;letter-spacing: 11.1px;font-family:'Lato', 'Open Sans', sans-serif;font-size:55px;line-height:46px;color:#101017;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:200;durationin:2500;delayin:1500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;"><span style="color:white; font-weight:900">Atornilladores </span> </div>
                        <div class="ls-l" style="top:158px;left:0px;font-weight:300; z-index:3;font-family:'Lato';font-size:30px;line-height:26px;color:#101017;white-space: nowrap;" data-ls="offsetxin:-100;durationin:2000;delayin:2500;">  <span style="color:#21c2f8;"></span> </div>
                        <img class="ls-l" style="top:0px;left:570px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-100;delayin:500;" src="/images/sliders/blank.gif" data-src="/images/Atornillador-de-Paro.jpg" alt="Atornillador de paro" title="Atornillador de paro">
                        <div class="ls-l" style="top:202px;left:0px;font-weight:normal; z-index:5; letter-spacing: 1.8px;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:30px;line-height:46px;color:#a2abb8;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:200;durationin:2500;delayin:3500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;">Tenemos los atornilladores ideales</div>
                        <div class="ls-l" style="top:242px;left:0px;font-weight:normal; z-index:5; letter-spacing: 7.3px;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:30px;line-height:46px;color:#a2abb8;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:200;durationin:2500;delayin:3500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;"><span style="color:#a2abb8;">para tu línea de ensamble</span> </div>
                        <p class="ls-l" style="top:313px;left:376px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:7000;"> <a href="/productos/atornilladores/" class="dt-sc-button1 ico-button"> Ver más</a></p>
                    </div>
                    <div class="ls-slide" data-ls="slidedelay:10000;transition2d:4;">
                        <img src="/images/sliders/blank.gif" data-src="/images/fondo-azul.jpg" class="ls-bg" alt="bg2" />
                        <div class="ls-l" style="top:157px;left:0px;font-weight:normal;letter-spacing:2.3px; z-index:5;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:40px;line-height:46px;color:#FFFFFF;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-100;durationin:2000;delayin:2500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;">Demoledores Neumáticos</div>
                        <p class="ls-l" style="top:341px;left:364px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:7000;"> <a href="/productos/rompedores/" class="dt-sc-button1 ico-button"> Ver más</a></p>
                        <img class="ls-l" style="top:0px;left:570px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:500;durationin:1800;" src="/images/sliders/blank.gif" data-src="/images/Rompedor-Cincelador-Neumatico.jpg" alt="Rompedor cincelador neumatico" title="Rompedor cincelador neumatico">
                        <div class="ls-l" style="top:235px;left:0px;font-weight:500;font-family:'Lato';font-size:27px;color:rgb(209,208,206);white-space: nowrap;" data-ls="delayin:5000;">Los <span style="color:rgb(209,208,206); font-weight:700;">  martillos, cinceladores y demoledores </span></div>
                        <div class="ls-l" style="top:283px;letter-spacing:3.5px;left:0px;font-weight:500;font-family:'Lato';font-size:27px;color:rgb(209,208,206);white-space: nowrap;" data-ls="delayin:5500;">más potentes los encuentras aquí<span style="color:#00a5df; font-weight:700;"> </span> </div>
                    </div>
                    <div class="ls-slide" data-ls="slidedelay:10000;transition2d:4;">
                        <img src="/images/sliders/blank.gif" data-src="/images/fondo-azul.jpg" class="ls-bg" alt="bg3" />
                        <div class="ls-l" style="top:206px;left:657px;font-weight:normal; letter-spacing:0px;z-index:3;font-family:'Lato';font-size:25px;line-height:26px;color:#a2abb8;white-space: nowrap;" data-ls="offsetxin:-100;durationin:2000;delayin:4000;">De casco, para tapizado y armado de muebles</div>
                        <div class="ls-l" style="top:130px;left:657px;font-weight:700;letter-spacing:15px; z-index:3;font-family:'Lato';font-size:53px;line-height:26px;color:white;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:50;durationin:2000;delayin:3000;"> Engrapadoras </div>
                        <div class="ls-l" style="top:035px;left:1166px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:3000;"><span style="background: #00a5df; color: #fff; display: inline-block; font-family: 'Lato', sans-serif; font-size: 20px; font-weight: 300; line-height: 24px; margin: 10px 0 0; padding: 0 7px 0 7px; position: relative; text-decoration: none; border-radius: 3px; -webkit-border-radius: 3px; -moz-border-radius: 3px; -ms-border-radius: 3px; -o-border-radius: 3px; "></span> </div>
                        <img class="ls-l" style="top:0px;left:0px;white-space: nowrap; " data-ls="offsetxin:0;offsetyin:300;durationin:1500;delayin:500;" src="/images/sliders/blank.gif" data-src="/images/Engrapadora-Neumatica.jpg" alt="Engrapadora neumatica" title="Engrapadora neumatica">
                        <p class="ls-l" style="top:270px;left:1020px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:7000;"> <a href="/productos/engrapadora/" class="dt-sc-button1 ico-button"> Ver más</a></p>
                    </div>
                    <div class="ls-slide" data-ls="slidedelay:10000;transition2d:4;">
                        <img src="/images/sliders/blank.gif" data-src="/images/fondo-azul.jpg" class="ls-bg" alt="bg1" />
                        <div class="ls-l" style="top:137px;left:0px;font-weight:300; letter-spacing:6.2px; z-index:5;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:40px;line-height:46px;color:#FFFFFF;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:200;durationin:2500;delayin:1500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;"><span style="color:#FFFFFF;font-weight:900">Lijadoras Airon Tools</span> </div>
                        <div class="ls-l" style="top:226px;left:0px;font-weight:300;letter-spacing:5.6px; z-index:3;font-family:'Lato';font-size:27px;line-height:26px;color:#FFFFFF;white-space: nowrap;" data-ls="offsetxin:-100;durationin:2000;delayin:2500;">Lograrás los mejores acabados<span style="color:#21c2f8;"></span></div>
                        <div class="ls-l" style="top:200px;left:0px;z-index: display:block;width:508px;height:2px;border-bottom:1px solid rgb(001,168,223);font-family:'Ubuntu';font-size:24px;line-height:34px;color:rgb(001,168,223);;background:rgb(001,168,223);white-space: nowrap;" data-ls="offsetxin:-500;durationin:2500;delayin:4500;"><br></div>
                        <img class="ls-l" style="top:0px;left:570px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-100;delayin:500;" src="/images/sliders/blank.gif" data-src="/images/Lijadora-orbital.jpg" alt="Lijadora orbital" title="Lijadora orbital">
                        <p class="ls-l" style="top:279px;left:375px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:7000;"> <a href="/productos/lijadoras/" class="dt-sc-button1 ico-button">Ver más</a></p>
                    </div>
                    <div class="ls-slide" data-ls="slidedelay:10000;transition2d:4;">
                        <img src="/images/sliders/blank.gif" data-src="/images/fondo-azul.jpg" class="ls-bg" alt="bg2" />
                        <div class="ls-l" style="top:149px;left:0px;font-weight:normal; letter-spacing: 4.5px;z-index:5;padding-left:0px;font-family:'Lato', 'Open Sans', sans-serif;font-size:43px;line-height:46px;color:#FFFFFF;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:-100;durationin:2000;delayin:2500;transformoriginin:left 50% 0;offsetxout:0;rotateyout:-90;transformoriginout:left 50% 0;">Herramientas de corte</div>
                        <div class="ls-l" style="top:257px;left:0px;font-weight:300; z-index:3; letter-spacing:5.5px;font-family:'Lato';font-size:43px;line-height:26px;color:#101017;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;durationin:2000;delayin:3500;"></div>
                        <div class="ls-l" style="top:323px;left:0px;font-weight:300;font-family:'Lato';font-size:18px;color:#101017;white-space: nowrap;" data-ls="delayin:4500;"><span style="color:#00a5df; font-weight:700;"></span></div>
                        <p class="ls-l" style="top:328px;left:372px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:100;delayin:7000;"> <a href="/productos/herramientas-de-corte/" class="dt-sc-button1 ico-button">Ver más</a></p>
                        <img class="ls-l" style="top:0px;left:570px;white-space: nowrap;" data-ls="offsetxin:0;offsetyin:500;durationin:1800;" src="/images/sliders/blank.gif" data-src="/images/Cizalla-Neumatica-Airon.jpg" alt="Cizalla neumatica" title="Cizalla neumatica">
                        <div class="ls-l" style="top:234px;left:0px;font-weight:300;letter-spacing:.5px;font-family:'Lato';font-size:27px;color:#C7C7C7;white-space: nowrap;" data-ls="delayin:5000;"><span style="color:#C7C7C7; font-weight:700;">Corta casi cualquier material con nuestra </span></div>
                        <div class="ls-l" style="top:269px;left:0px;font-weight:300;letter-spacing:5px;font-family:'Lato';font-size:27px;color:#C7C7C7;white-space: nowrap;" data-ls="delayin:5500;"><span style="color:#C7C7C7; font-weight:700;">gama de herramientas de corte</span> </div>
                    </div>

                </div>

            </div><!-- **banner - Ends** -->